/// Mapping between Whisper ISO 639-1 language codes and NLLB language codes.
class LanguageCodes {
  LanguageCodes._();

  /// Whisper ISO 639-1 code -> NLLB flores200 code
  static const Map<String, String> whisperToNllb = {
    'af': 'afr_Latn',
    'am': 'amh_Ethi',
    'ar': 'arb_Arab',
    'as': 'asm_Beng',
    'az': 'azj_Latn',
    'ba': 'bak_Cyrl',
    'be': 'bel_Cyrl',
    'bg': 'bul_Cyrl',
    'bn': 'ben_Beng',
    'bo': 'bod_Tibt',
    'br': 'bre_Latn',
    'bs': 'bos_Latn',
    'ca': 'cat_Latn',
    'cs': 'ces_Latn',
    'cy': 'cym_Latn',
    'da': 'dan_Latn',
    'de': 'deu_Latn',
    'el': 'ell_Grek',
    'en': 'eng_Latn',
    'es': 'spa_Latn',
    'et': 'est_Latn',
    'eu': 'eus_Latn',
    'fa': 'pes_Arab',
    'fi': 'fin_Latn',
    'fo': 'fao_Latn',
    'fr': 'fra_Latn',
    'gl': 'glg_Latn',
    'gu': 'guj_Gujr',
    'ha': 'hau_Latn',
    'haw': 'haw_Latn',
    'he': 'heb_Hebr',
    'hi': 'hin_Deva',
    'hr': 'hrv_Latn',
    'ht': 'hat_Latn',
    'hu': 'hun_Latn',
    'hy': 'hye_Armn',
    'id': 'ind_Latn',
    'is': 'isl_Latn',
    'it': 'ita_Latn',
    'ja': 'jpn_Jpan',
    'jw': 'jav_Latn',
    'ka': 'kat_Geor',
    'kk': 'kaz_Cyrl',
    'km': 'khm_Khmr',
    'kn': 'kan_Knda',
    'ko': 'kor_Hang',
    'la': 'lat_Latn',
    'lb': 'ltz_Latn',
    'ln': 'lin_Latn',
    'lo': 'lao_Laoo',
    'lt': 'lit_Latn',
    'lv': 'lvs_Latn',
    'mg': 'plt_Latn',
    'mi': 'mri_Latn',
    'mk': 'mkd_Cyrl',
    'ml': 'mal_Mlym',
    'mn': 'khk_Cyrl',
    'mr': 'mar_Deva',
    'ms': 'zsm_Latn',
    'mt': 'mlt_Latn',
    'my': 'mya_Mymr',
    'ne': 'npi_Deva',
    'nl': 'nld_Latn',
    'nn': 'nno_Latn',
    'no': 'nob_Latn',
    'oc': 'oci_Latn',
    'pa': 'pan_Guru',
    'pl': 'pol_Latn',
    'ps': 'pbt_Arab',
    'pt': 'por_Latn',
    'ro': 'ron_Latn',
    'ru': 'rus_Cyrl',
    'sa': 'san_Deva',
    'sd': 'snd_Arab',
    'si': 'sin_Sinh',
    'sk': 'slk_Latn',
    'sl': 'slv_Latn',
    'sn': 'sna_Latn',
    'so': 'som_Latn',
    'sq': 'als_Latn',
    'sr': 'srp_Cyrl',
    'su': 'sun_Latn',
    'sv': 'swe_Latn',
    'sw': 'swh_Latn',
    'ta': 'tam_Taml',
    'te': 'tel_Telu',
    'tg': 'tgk_Cyrl',
    'th': 'tha_Thai',
    'tk': 'tuk_Latn',
    'tl': 'tgl_Latn',
    'tr': 'tur_Latn',
    'tt': 'tat_Cyrl',
    'uk': 'ukr_Cyrl',
    'ur': 'urd_Arab',
    'uz': 'uzn_Latn',
    'vi': 'vie_Latn',
    'yi': 'ydd_Hebr',
    'yo': 'yor_Latn',
    'zh': 'zho_Hans',
    'zu': 'zul_Latn',
  };

  /// Reverse mapping: NLLB code -> Whisper ISO 639-1 code
  static final Map<String, String> nllbToWhisper = {
    for (final entry in whisperToNllb.entries) entry.value: entry.key,
  };

  /// Human-readable language names
  static const Map<String, String> languageNames = {
    'af': 'Afrikaans',
    'am': 'Amharic',
    'ar': 'Arabic',
    'as': 'Assamese',
    'az': 'Azerbaijani',
    'ba': 'Bashkir',
    'be': 'Belarusian',
    'bg': 'Bulgarian',
    'bn': 'Bengali',
    'bo': 'Tibetan',
    'br': 'Breton',
    'bs': 'Bosnian',
    'ca': 'Catalan',
    'cs': 'Czech',
    'cy': 'Welsh',
    'da': 'Danish',
    'de': 'German',
    'el': 'Greek',
    'en': 'English',
    'es': 'Spanish',
    'et': 'Estonian',
    'eu': 'Basque',
    'fa': 'Persian',
    'fi': 'Finnish',
    'fo': 'Faroese',
    'fr': 'French',
    'gl': 'Galician',
    'gu': 'Gujarati',
    'ha': 'Hausa',
    'haw': 'Hawaiian',
    'he': 'Hebrew',
    'hi': 'Hindi',
    'hr': 'Croatian',
    'ht': 'Haitian Creole',
    'hu': 'Hungarian',
    'hy': 'Armenian',
    'id': 'Indonesian',
    'is': 'Icelandic',
    'it': 'Italian',
    'ja': 'Japanese',
    'jw': 'Javanese',
    'ka': 'Georgian',
    'kk': 'Kazakh',
    'km': 'Khmer',
    'kn': 'Kannada',
    'ko': 'Korean',
    'la': 'Latin',
    'lb': 'Luxembourgish',
    'ln': 'Lingala',
    'lo': 'Lao',
    'lt': 'Lithuanian',
    'lv': 'Latvian',
    'mg': 'Malagasy',
    'mi': 'Maori',
    'mk': 'Macedonian',
    'ml': 'Malayalam',
    'mn': 'Mongolian',
    'mr': 'Marathi',
    'ms': 'Malay',
    'mt': 'Maltese',
    'my': 'Myanmar',
    'ne': 'Nepali',
    'nl': 'Dutch',
    'nn': 'Nynorsk',
    'no': 'Norwegian',
    'oc': 'Occitan',
    'pa': 'Punjabi',
    'pl': 'Polish',
    'ps': 'Pashto',
    'pt': 'Portuguese',
    'ro': 'Romanian',
    'ru': 'Russian',
    'sa': 'Sanskrit',
    'sd': 'Sindhi',
    'si': 'Sinhala',
    'sk': 'Slovak',
    'sl': 'Slovenian',
    'sn': 'Shona',
    'so': 'Somali',
    'sq': 'Albanian',
    'sr': 'Serbian',
    'su': 'Sundanese',
    'sv': 'Swedish',
    'sw': 'Swahili',
    'ta': 'Tamil',
    'te': 'Telugu',
    'tg': 'Tajik',
    'th': 'Thai',
    'tk': 'Turkmen',
    'tl': 'Tagalog',
    'tr': 'Turkish',
    'tt': 'Tatar',
    'uk': 'Ukrainian',
    'ur': 'Urdu',
    'uz': 'Uzbek',
    'vi': 'Vietnamese',
    'yi': 'Yiddish',
    'yo': 'Yoruba',
    'zh': 'Chinese',
    'zu': 'Zulu',
  };

  static String? toNllb(String whisperCode) => whisperToNllb[whisperCode];

  static String? toWhisper(String nllbCode) => nllbToWhisper[nllbCode];

  static String getLanguageName(String whisperCode) =>
      languageNames[whisperCode] ?? whisperCode;
}
