import 'dart:ffi';
import 'dart:io';

import 'package:ffi/ffi.dart';

/// FFI bindings for the whisper_bridge native library.
/// In production, these would be generated by ffigen from whisper_bridge.h.

// Native types
typedef WhisperBridgeContextNative = Void;

final class WhisperBridgeResult extends Struct {
  external Pointer<Utf8> text;
  external Pointer<Utf8> language;

  @Float()
  external double languageProbability;
}

// C function signatures
typedef WhisperBridgeInitNative = Pointer<WhisperBridgeContextNative> Function(
  Pointer<Utf8> modelPath,
);
typedef WhisperBridgeInitDart = Pointer<WhisperBridgeContextNative> Function(
  Pointer<Utf8> modelPath,
);

typedef WhisperBridgeFreeNative = Void Function(
  Pointer<WhisperBridgeContextNative> ctx,
);
typedef WhisperBridgeFreeDart = void Function(
  Pointer<WhisperBridgeContextNative> ctx,
);

typedef WhisperBridgeTranscribeNative = Pointer<WhisperBridgeResult> Function(
  Pointer<WhisperBridgeContextNative> ctx,
  Pointer<Float> samples,
  Int32 nSamples,
  Int32 detectLanguage,
);
typedef WhisperBridgeTranscribeDart = Pointer<WhisperBridgeResult> Function(
  Pointer<WhisperBridgeContextNative> ctx,
  Pointer<Float> samples,
  int nSamples,
  int detectLanguage,
);

typedef WhisperBridgeFreeResultNative = Void Function(
  Pointer<WhisperBridgeResult> result,
);
typedef WhisperBridgeFreeResultDart = void Function(
  Pointer<WhisperBridgeResult> result,
);

class WhisperBindings {
  late final DynamicLibrary _lib;
  late final WhisperBridgeInitDart init;
  late final WhisperBridgeFreeDart free;
  late final WhisperBridgeTranscribeDart transcribe;
  late final WhisperBridgeFreeResultDart freeResult;

  WhisperBindings() {
    _lib = _loadLibrary();
    init = _lib
        .lookupFunction<WhisperBridgeInitNative, WhisperBridgeInitDart>(
          'whisper_bridge_init',
        );
    free = _lib
        .lookupFunction<WhisperBridgeFreeNative, WhisperBridgeFreeDart>(
          'whisper_bridge_free',
        );
    transcribe = _lib
        .lookupFunction<
          WhisperBridgeTranscribeNative,
          WhisperBridgeTranscribeDart
        >('whisper_bridge_transcribe');
    freeResult = _lib
        .lookupFunction<
          WhisperBridgeFreeResultNative,
          WhisperBridgeFreeResultDart
        >('whisper_bridge_free_result');
  }

  static DynamicLibrary _loadLibrary() {
    if (Platform.isAndroid) {
      return DynamicLibrary.open('libwhisper_bridge.so');
    } else if (Platform.isIOS) {
      return DynamicLibrary.process();
    }
    throw UnsupportedError('Unsupported platform: ${Platform.operatingSystem}');
  }
}
